#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 3 -yoffset 20 -xoffset -0 -width 15 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 -font "Fira Code Nerd Font Regular 14" <<< " Lock| Logout| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) blurlock ;;
                *Logout) i3-msg exit;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
esac
